db:
  driver: org.postgresql.Driver
  user: postgres
  password: postgres
  poolsize: 8
  url: jdbc:postgresql://localhost:5432/clever_bank
  
##################################################
url:
  author: controller?command=author_page
  main: controller?command=main_page
  account: controller?command=account_page
  catalog: controller?command=catalog_page
  error: /controller?command=error_page
#  reader.order=controller?command=reader_book_order_page
#  librarian.order=controller?command=librarian_book_order_page

##################################################

table:
  id: id
  name: name
  login: login
  pass: password
  balance: balance
  bank_account_id_from: bank_account_id_from
  bank_account_id_to: bank_account_id_to
  sum: sum
