db:
  driver: org.postgresql.Driver
  user: postgres
  password: postgres
  poolsize: 8
  url: jdbc:postgresql://localhost:5432/clever_bank
  
##################################################
url:
  author: controller?command=author_page
  main: controller?command=main_page
  account: controller?command=account_page
  catalog: controller?command=catalog_page
  error: /controller?command=error_page
#  reader.order=controller?command=reader_book_order_page
#  librarian.order=controller?command=librarian_book_order_page

##################################################

table:
  id: id
  name: name
  login: login
  pass: password
  balance: balance
  bank_account_id_from: bank_account_id_from
  bank_account_id_to: bank_account_id_to
  sum: sum
  owner_ba_id: owner_ba_id
  owner_ba_balance: owner_ba_balance
  user_ba_id: user_ba_id
  user_ba_balance: user_ba_balance
  owner_account_id: owner_account_id
  owner_account_login: owner_account_login
  user_account_id: user_account_id
  user_account_login: user_account_login

###################################################

pdf:
  template: template.pdf
  bill_id: bill_id
  date: date
  time: time
  type: type
  bank_sender: bank_sender
  bank_recipient: bank_recipient
  ba_sender: ba_sender
  ba_recipient: ba_recipient
  amount: amount
  path.save: check/bill%s.pdf
