db:
  driver: org.postgresql.Driver
  user: postgres
  password: postgres
  poolsize: 8
  url: jdbc:postgresql://localhost:5432/clever_bank

#################################################
accrual:
  percentage: 0.01

bank:
  id: 1
  name: clever_bank

##################################################
table:
  id: id
  name: name
  login: login
  pass: password
  balance: balance
  bank_account_id_from: bank_account_id_from
  bank_account_id_to: bank_account_id_to
  sum: sum
  owner_ba_id: owner_ba_id
  owner_ba_balance: owner_ba_balance
  user_ba_id: user_ba_id
  user_ba_balance: user_ba_balance
  owner_account_id: owner_account_id
  owner_account_login: owner_account_login
  user_account_id: user_account_id
  user_account_login: user_account_login
  owner_date_create: owner_ba_date_create
  user_date_create: user_ba_date_create
  date_create: date_create
  type: type

###################################################
path:
  bill: check/bill%s_%s.txt
  statement.txt: statement/statement%s_%s.txt
  statement.pdf: statement/statement%s_%s.pdf
  bill.template: template.pdf
  statement.template: statement.pdf

#######################################################
operation:
  replenishment: Replenishment
  withdrawal: Withdrawal
  transaction: Transaction

